server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cust_db
    username: postgres
    password: admin123
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost